# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Astro CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  SERVER_IP: ${{ secrets.SERVER_IP }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Generate private key
        run: |
          echo "${{ secrets.AWS_SECRET_KEY }}" > CD-CI.pem
          chmod 400 CD-CI.pem

      - name: Generate .env file
        run: |
          echo "${{ secrets.VAR_ENV }}" > .env

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: 'node_modules'
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies if cache not found
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Build app
        run: pnpm astro build

      - name: Sync files to server
        run: |
          scp -i CD-CI.pem -o StrictHostKeyChecking=no -r ./dist ./package.json app@${{ secrets.SERVER_IP }}:/home/app/test/
          ssh -i CD-CI.pem -o StrictHostKeyChecking=no app@{{ secrets.SERVER_IP }} "source ~/.nvm/nvm.sh && cd /home/app/test && /home/app/.local/share/pnpm/pnpm install"
          ssh -i CD-CI.pem -o StrictHostKeyChecking=no app@{{ secrets.SERVER_IP }} "source ~/.nvm/nvm.sh && /home/app/.local/share/pnpm/pm2 restart uhernandez.com"
